<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.ac.fage.accessmesh</groupId>
        <artifactId>accessmesh</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>perm-sdk</artifactId>
    <packaging>pom</packaging>
    <name>Permission SDK</name>
    <description>Permission center SDK starters</description>

    <modules>
        <module>perm-common</module>
        <module>perm-client-spring-boot-starter</module>
        <module>perm-gateway-spring-boot-starter</module>
        <module>perm-data-spring-boot-starter</module>
    </modules>
</project>
