spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false
  jackson:
    date-time-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

cache:
  caffeine:
    spec: maximumSize=1000,expireAfterWrite=10m

perm:
  cache:
    l1-enabled: true
    l2-enabled: true
    default-ttl-minutes: 30

logging:
  level:
    cn.ac.fage.accessmesh: INFO
    org.springframework.cloud.loadbalancer: WARN
