spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false
  jackson:
    date-time-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

perm:
  cache:
    l1:
      maximum-size: 1000
      expire-minutes: 10
    l2:
      ttl-minutes: 30

logging:
  level:
    cn.ac.fage.accessmesh: INFO
    org.springframework.cloud.loadbalancer: WARN
