package cn.ac.fage.accessmesh.access.permission.mapper;

import com.mybatisflex.core.BaseMapper;
import cn.ac.fage.accessmesh.access.permission.entity.AbstractUser;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

/**
 * 抽象用户数据访问接口
 * <p>
 * 提供抽象用户表的基础CRUD操作和自定义查询方法。
 * 抽象用户包括内部用户和外部用户，是权限分配的主体。
 * 支持批量软删除操作。
 * </p>
 */
public interface AbstractUserMapper extends BaseMapper<AbstractUser> {

    /**
     * 显式 id 插入（T-ORG-001 本地主体创建专用）。
     * <p>
     * 实体 {@code @Id(keyType = KeyType.Auto)} 使 Flex 通用 insert 忽略已设置的 id
     * （外部主体依赖自增取号，保持不动）；本地主体必须以预取的序列值 N 显式落库，
     * 故走本方法旁路 keygen。extra 为 JSONB，typeHandler 与实体列注解一致。
     * </p>
     *
     * @param user 已设置 id 的主体行
     * @return 插入行数
     */
    @Insert(
        "INSERT INTO abstract_user (id, tenant_id, user_type, external_id, name, enabled, extra, "
            + "owner_service_code, created_at, updated_at, delete_flag) "
            + "VALUES (#{id}, #{tenantId}, #{userType}, #{externalId}, #{name}, #{enabled}, "
            + "#{extra, typeHandler=cn.ac.fage.accessmesh.access.infrastructure.JsonbStringTypeHandler}, "
            + "#{ownerServiceCode}, #{createdAt}, #{updatedAt}, #{deleteFlag})")
    int insertWithExplicitId(AbstractUser user);

    /**
     * 预取下一个主体 ID（T-ORG-001，architecture §12.2）。
     * <p>
     * {@code abstract_user.id} 的 BIGSERIAL 序列是唯一主体 ID 生成源：本地用户创建
     * 先经本方法取号 N，再显式同 ID 插 abstract_user(id=N, external_id=N) 与
     * sys_user(id=N)；外部主体仅插 abstract_user（自增取号），共用同一序列天然不碰撞。
     * serial 列显式插值合法（GENERATED BY DEFAULT 语义），序列水位由本取号推进。
     * </p>
     *
     * @return 预取的主体 ID
     */
    @Select("SELECT nextval(pg_get_serial_sequence('abstract_user', 'id'))")
    Long nextSubjectId();

    /**
     * 批量软删除抽象用户
     * <p>
     * 将指定用户的delete_flag设置为id，deleted_at设置为当前时间。
     * 用于批量删除场景，避免物理删除。
     * </p>
     *
     * @param tenantId  租户ID
     * @param ids       待删除的抽象用户ID列表
     * @param deletedAt 删除时间戳
     * @return 更新的行数
     */
    int softDeleteBatch(@Param("tenantId") Long tenantId,
                        @Param("ids") List<Long> ids,
                        @Param("deletedAt") LocalDateTime deletedAt);

    /**
     * 根据ID和租户ID查询有效用户
     *
     * @param id       用户ID
     * @param tenantId 租户ID
     * @return 用户实体，不存在或已删除返回null
     */
    AbstractUser selectValidById(@Param("id") Long id, @Param("tenantId") Long tenantId);

    /**
     * 根据用户类型、外部ID和租户ID查询有效用户（用于sync/create唯一性检查）
     *
     * @param tenantId  租户ID
     * @param userType  用户类型值
     * @param externalId 用户外部ID
     * @return 用户实体，不存在返回null
     */
    AbstractUser selectByTypeAndExternalId(@Param("tenantId") Long tenantId,
                                            @Param("userType") Integer userType,
                                            @Param("externalId") String externalId);

    /**
     * 根据ID集合批量查询有效用户
     *
     * @param tenantId 租户ID
     * @param ids      用户ID集合
     * @return 用户列表
     */
    List<AbstractUser> selectValidByIds(@Param("tenantId") Long tenantId, @Param("ids") Set<Long> ids);

    /**
     * 分页查询用户列表（带过滤条件）
     *
     * @param tenantId        租户ID
     * @param userType        用户类型值，可选
     * @param keyword         搜索关键字，可选（LIKE匹配name或external_id）
     * @param matchNone       是否匹配空结果（用于域过滤不匹配时）
     * @param offset          偏移量
     * @param limit           每页数量
     * @return 用户列表
     */
    List<AbstractUser> selectUserListPaged(@Param("tenantId") Long tenantId,
                                            @Param("userType") Integer userType,
                                            @Param("keyword") String keyword,
                                            @Param("matchNone") boolean matchNone,
                                            @Param("offset") int offset,
                                            @Param("limit") int limit);

    /**
     * 统计用户数量（带过滤条件）
     *
     * @param tenantId        租户ID
     * @param userType        用户类型值，可选
     * @param keyword         搜索关键字，可选
     * @param matchNone       是否匹配空结果
     * @return 用户总数
     */
    long selectUserListCount(@Param("tenantId") Long tenantId,
                              @Param("userType") Integer userType,
                              @Param("keyword") String keyword,
                              @Param("matchNone") boolean matchNone);

    /**
     * 根据用户类型和外部ID批量查询有效用户
     *
     * @param tenantId    租户ID
     * @param userType    用户类型值
     * @param externalIds 外部ID集合
     * @return 用户列表
     */
    List<AbstractUser> selectByTypeAndExternalIds(@Param("tenantId") Long tenantId,
                                                   @Param("userType") Integer userType,
                                                   @Param("externalIds") Set<String> externalIds);

    /**
     * 批量停用抽象用户（enabled=false，单条 SQL，启停路径批量 N+1 消除）
     *
     * @param tenantId  租户ID
     * @param ids       抽象用户ID集合
     * @param updatedAt 更新时间
     * @return 影响行数
     */
    int batchDisable(@Param("tenantId") Long tenantId,
                     @Param("ids") Set<Long> ids,
                     @Param("updatedAt") LocalDateTime updatedAt);

    /**
     * 批量刷新已有投影行的 name/enabled/extra（batchUpsert 已有行路径，单条 SQL 替代循环 update）。
     * <p>
     * 每行值不同，使用 PostgreSQL {@code UPDATE ... FROM (VALUES ...)} 惯用法（项目为 PG 方言）；
     * extra 为 null 的行保留原值（与单条路径"仅非 null 才更新"语义一致）。
     * </p>
     *
     * @param tenantId  租户ID
     * @param owner     所有者服务编码
     * @param users     待刷新行（必须含主键 id）
     * @param updatedAt 更新时间
     * @return 影响行数
     */
    int batchUpdateValues(@Param("tenantId") Long tenantId,
                          @Param("owner") String owner,
                          @Param("users") List<AbstractUser> users,
                          @Param("updatedAt") LocalDateTime updatedAt);
}