/** 管理台领域值；与服务端公开契约保持同值，测试夹具可使用字面值验证线格式。 */
export const ORG_TYPE = { ORG: 1, POSITION: 2 } as const;
export const SUBJECT_TYPE = { LOCAL_USER: "LOCAL_USER" } as const;
export const DEFAULT_PAGE_SIZE = 20;
/** 完整枚举仍须按 hasNext 循环，200 只是每次取数上限。 */
export const ENUM_PAGE_SIZE = 200;
export const OPERATION_CODE = {
  VIEW: "VIEW",
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE"
} as const;
export const PERMISSION_CODE = {
  CONDITION_CREATE: "CONDITION:CREATE",
  CONDITION_DELETE: "CONDITION:DELETE",
  CONDITION_UPDATE: "CONDITION:UPDATE",
  CONDITION_VIEW: "CONDITION:VIEW",
  CONFLICT_RULE_CREATE: "CONFLICT_RULE:CREATE",
  CONFLICT_RULE_DELETE: "CONFLICT_RULE:DELETE",
  CONFLICT_RULE_UPDATE: "CONFLICT_RULE:UPDATE",
  CONFLICT_RULE_VIEW: "CONFLICT_RULE:VIEW",
  DEPENDENCY_VIEW: "DEPENDENCY:VIEW",
  DOMAIN_VIEW: "DOMAIN:VIEW",
  OPERATION_CREATE: "OPERATION:CREATE",
  OPERATION_MANAGE: "OPERATION:MANAGE",
  OPERATION_VIEW: "OPERATION:VIEW",
  OPERATION_LOG_VIEW: "OPERATION_LOG:VIEW",
  ORG_ASSIGN_POSITION_USER: "ORG:ASSIGN_POSITION_USER",
  ORG_CREATE: "ORG:CREATE",
  ORG_CREATE_POSITION: "ORG:CREATE_POSITION",
  ORG_DELETE: "ORG:DELETE",
  ORG_DELETE_POSITION: "ORG:DELETE_POSITION",
  ORG_MANAGE_MEMBER: "ORG:MANAGE_MEMBER",
  ORG_UPDATE: "ORG:UPDATE",
  ORG_UPDATE_POSITION: "ORG:UPDATE_POSITION",
  ORG_VIEW: "ORG:VIEW",
  ORG_VIEW_POSITION: "ORG:VIEW_POSITION",
  PERMISSION_CHANGE_LOG_VIEW: "PERMISSION_CHANGE_LOG:VIEW",
  RESOURCE_CREATE: "RESOURCE:CREATE",
  RESOURCE_MANAGE: "RESOURCE:MANAGE",
  RESOURCE_VIEW: "RESOURCE:VIEW",
  ROLE_CREATE: "ROLE:CREATE",
  ROLE_MANAGE: "ROLE:MANAGE",
  ROLE_VIEW: "ROLE:VIEW",
  SERVICE_MANAGE: "SERVICE:MANAGE",
  SERVICE_MANAGE_API_MAPPING: "SERVICE:MANAGE_API_MAPPING",
  SERVICE_SYNC_INTERFACE: "SERVICE:SYNC_INTERFACE",
  SERVICE_VIEW: "SERVICE:VIEW",
  SYSTEM_CONFIG_MANAGE: "SYSTEM_CONFIG:MANAGE",
  SYSTEM_CONFIG_VIEW: "SYSTEM_CONFIG:VIEW",
  TYPE_DEFINITION_CREATE: "TYPE_DEFINITION:CREATE",
  TYPE_DEFINITION_MANAGE: "TYPE_DEFINITION:MANAGE",
  TYPE_DEFINITION_VIEW: "TYPE_DEFINITION:VIEW",
  USER_CREATE: "USER:CREATE",
  USER_DELETE: "USER:DELETE",
  USER_ENABLE: "USER:ENABLE",
  USER_RESET_PASSWORD: "USER:RESET_PASSWORD",
  USER_UPDATE: "USER:UPDATE",
  USER_VIEW: "USER:VIEW"
} as const;
